// <auto-generated />
using System;
using Kolos2_Muzycy.Enitities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos2_Muzycy.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20240606210143_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlbum"));

                    b.Property<DateTime>("DataWydania")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("NazwaAlbumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAlbum")
                        .HasName("IdAlbum");

                    b.HasIndex("IdWytwornia");

                    b.ToTable("Album", (string)null);

                    b.HasData(
                        new
                        {
                            IdAlbum = 1,
                            DataWydania = new DateTime(2024, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            IdWytwornia = 1,
                            NazwaAlbumu = "album1"
                        },
                        new
                        {
                            IdAlbum = 2,
                            DataWydania = new DateTime(2024, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            IdWytwornia = 1,
                            NazwaAlbumu = "album2"
                        },
                        new
                        {
                            IdAlbum = 3,
                            DataWydania = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            IdWytwornia = 2,
                            NazwaAlbumu = "album3"
                        });
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMuzyk"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Pseudonim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk")
                        .HasName("IdMuzyk");

                    b.ToTable("Muzyk", (string)null);

                    b.HasData(
                        new
                        {
                            IdMuzyk = 1,
                            Imie = "Adam",
                            Nazwisko = "Nowak",
                            Pseudonim = "Adasio200"
                        },
                        new
                        {
                            IdMuzyk = 2,
                            Imie = "Adrianna",
                            Nazwisko = "Malinowska"
                        });
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtwor"));

                    b.Property<float>("CzasTrwania")
                        .HasColumnType("real");

                    b.Property<int>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor")
                        .HasName("IdUtwor");

                    b.ToTable("Utwor", (string)null);

                    b.HasData(
                        new
                        {
                            IdUtwor = 1,
                            CzasTrwania = 2.2f,
                            IdAlbum = 1,
                            NazwaUtworu = "al1na1"
                        },
                        new
                        {
                            IdUtwor = 2,
                            CzasTrwania = 3.3f,
                            IdAlbum = 1,
                            NazwaUtworu = "al1na2"
                        },
                        new
                        {
                            IdUtwor = 3,
                            CzasTrwania = 5.5f,
                            IdAlbum = 2,
                            NazwaUtworu = "al12na1"
                        });
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Wytwornia", b =>
                {
                    b.Property<int>("IdWytwornia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWytwornia"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdWytwornia")
                        .HasName("IdWytwornia");

                    b.ToTable("Wytwornia", (string)null);

                    b.HasData(
                        new
                        {
                            IdWytwornia = 1,
                            Nazwa = "Jasie"
                        },
                        new
                        {
                            IdWytwornia = 2,
                            Nazwa = "Muchy"
                        });
                });

            modelBuilder.Entity("WykonawcaUtworu", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.HasKey("IdMuzyk", "IdUtwor");

                    b.HasIndex("IdUtwor");

                    b.ToTable("WykonawcaUtworu");

                    b.HasData(
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 1
                        },
                        new
                        {
                            IdMuzyk = 2,
                            IdUtwor = 1
                        },
                        new
                        {
                            IdMuzyk = 1,
                            IdUtwor = 2
                        },
                        new
                        {
                            IdMuzyk = 2,
                            IdUtwor = 3
                        });
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Album", b =>
                {
                    b.HasOne("Kolos2_Muzycy.Enitities.Wytwornia", "NavigationWytwornia")
                        .WithMany("Albumy")
                        .HasForeignKey("IdWytwornia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NavigationWytwornia");
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Utwor", b =>
                {
                    b.HasOne("Kolos2_Muzycy.Enitities.Album", "NavigationAlbum")
                        .WithMany("UtworyAlbum")
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NavigationAlbum");
                });

            modelBuilder.Entity("WykonawcaUtworu", b =>
                {
                    b.HasOne("Kolos2_Muzycy.Enitities.Muzyk", null)
                        .WithMany()
                        .HasForeignKey("IdMuzyk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2_Muzycy.Enitities.Utwor", null)
                        .WithMany()
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Album", b =>
                {
                    b.Navigation("UtworyAlbum");
                });

            modelBuilder.Entity("Kolos2_Muzycy.Enitities.Wytwornia", b =>
                {
                    b.Navigation("Albumy");
                });
#pragma warning restore 612, 618
        }
    }
}
